name: Release Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  opencode:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run OpenCode
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          TELEGRAM_NOTIFY: ${{ secrets.TELEGRAM_NOTIFY }}
          PROMPT: |-
            Github Repo: ${{ github.repository }}
            /release-sync
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npx -y opencode-ai run -m opencode/big-pickle '${{ env.PROMPT }}'
